local opt = vim.opt

opt.number  = true --line numbers
opt.relativenumber = true -- relative line numbers
opt.backup = false -- creates a backup
opt.clipboard = "unnamedplus" -- system clipboard
opt.swapfile = false -- disable swapfile
opt.mouse = "a"
opt.showmode = false -- no -- INSERT -- or other modes
opt.splitright = true --split right
opt.splitbelow = true --split below
opt.cursorline = true -- show cursorline
opt.expandtab = true -- make tabs spavces
opt.shiftwidth = 2 -- spaces per indent
opt.tabstop = 2 -- spaces for a tab
opt.showtabline = 2 -- show tabs on top of windo -- show tabs on top of windoww
opt.smartcase = true
opt.smartindent = true -- make indenting great again
opt.ignorecase = true --ignore case when searching
opt.hlsearch = true -- hightlight searches
opt.fileencoding = "utf-8" --set utf-8 as encoding
opt.wrap = false -- do not wrap show on line
opt.undofile = true -- undofile enabled
